import 'atlas_exercise.dart';
import 'exercise_categories.dart';

/// Fuente de verdad de ejercicios en Atlas.
///
/// Población inicial: 30 ejercicios (migrados de ExerciseCatalog + metadata extendida).
/// Capacidad objetivo: 150+ ejercicios.
/// Los consumidores deben usar ExerciseSearch para queries; no iterar _all directamente.
class AtlasExerciseLibrary {
  const AtlasExerciseLibrary._();

  static const List<AtlasExercise> _all = [

    // ── Pecho ──────────────────────────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_pecho_001',
      name: 'Press de Banca',
      muscleGroup: MuscleGroup.pecho,
      equipment: Equipment.barra,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.compound,
      primaryMuscles: ['Pectoral mayor'],
      secondaryMuscles: ['Deltoides anterior', 'Tríceps braquial'],
      aliases: ['press banca', 'bench press', 'press de banco', 'banca plana', 'banca'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.strength],
    ),
    AtlasExercise(
      id: 'ex_pecho_002',
      name: 'Press Inclinado',
      muscleGroup: MuscleGroup.pecho,
      equipment: Equipment.mancuernas,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.compound,
      primaryMuscles: ['Pectoral mayor (porción clavicular)'],
      secondaryMuscles: ['Deltoides anterior', 'Tríceps braquial'],
      aliases: ['press inclinado', 'incline press', 'press inclinado mancuernas', 'incline dumbbell press'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.strength],
    ),
    AtlasExercise(
      id: 'ex_pecho_003',
      name: 'Aperturas',
      muscleGroup: MuscleGroup.pecho,
      equipment: Equipment.mancuernas,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Pectoral mayor'],
      secondaryMuscles: ['Deltoides anterior'],
      aliases: ['aperturas', 'flyes', 'apertura', 'dumbbell flyes', 'chest flyes'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss],
    ),
    AtlasExercise(
      id: 'ex_pecho_004',
      name: 'Fondos en Paralelas',
      muscleGroup: MuscleGroup.pecho,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.compound,
      primaryMuscles: ['Pectoral mayor (porción esternal)'],
      secondaryMuscles: ['Tríceps braquial', 'Deltoides anterior'],
      aliases: ['fondos', 'dips', 'paralelas', 'fondos paralelas', 'chest dips'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.strength, TrainingGoal.athletic],
    ),
    AtlasExercise(
      id: 'ex_pecho_005',
      name: 'Press con Cable Cruzado',
      muscleGroup: MuscleGroup.pecho,
      equipment: Equipment.cable,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Pectoral mayor'],
      secondaryMuscles: ['Deltoides anterior'],
      aliases: ['cable cruzado', 'crossover', 'cruce de poleas', 'cable crossover', 'cruces de cable'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss],
    ),

    // ── Espalda ────────────────────────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_espalda_001',
      name: 'Dominadas',
      muscleGroup: MuscleGroup.espalda,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.compound,
      primaryMuscles: ['Dorsal ancho'],
      secondaryMuscles: ['Bíceps braquial', 'Romboides', 'Trapecio'],
      aliases: ['dominadas', 'pull up', 'pullup', 'pull ups', 'chin up'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.strength, TrainingGoal.athletic],
    ),
    AtlasExercise(
      id: 'ex_espalda_002',
      name: 'Remo con Barra',
      muscleGroup: MuscleGroup.espalda,
      equipment: Equipment.barra,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.compound,
      primaryMuscles: ['Dorsal ancho', 'Romboides'],
      secondaryMuscles: ['Bíceps braquial', 'Trapecio medio'],
      aliases: ['remo barra', 'barbell row', 'remo inclinado', 'bent over row', 'remo con barra'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.strength],
    ),
    AtlasExercise(
      id: 'ex_espalda_003',
      name: 'Remo con Mancuerna',
      muscleGroup: MuscleGroup.espalda,
      equipment: Equipment.mancuernas,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Dorsal ancho', 'Romboides'],
      secondaryMuscles: ['Bíceps braquial'],
      aliases: ['remo mancuerna', 'dumbbell row', 'remo unilateral', 'one arm row', 'remo a una mano'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss, TrainingGoal.health],
    ),
    AtlasExercise(
      id: 'ex_espalda_004',
      name: 'Jalón al Pecho',
      muscleGroup: MuscleGroup.espalda,
      equipment: Equipment.maquina,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Dorsal ancho'],
      secondaryMuscles: ['Bíceps braquial', 'Romboides'],
      aliases: ['jalon', 'jalon pecho', 'lat pulldown', 'jalón', 'jalones', 'polea alta'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss, TrainingGoal.health],
    ),
    AtlasExercise(
      id: 'ex_espalda_005',
      name: 'Remo en Polea Baja',
      muscleGroup: MuscleGroup.espalda,
      equipment: Equipment.cable,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Dorsal ancho', 'Romboides'],
      secondaryMuscles: ['Bíceps braquial', 'Trapecio medio'],
      aliases: ['remo polea', 'seated row', 'remo polea baja', 'remo sentado', 'cable row'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss, TrainingGoal.health],
    ),

    // ── Hombros ────────────────────────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_hombros_001',
      name: 'Press Militar',
      muscleGroup: MuscleGroup.hombros,
      equipment: Equipment.barra,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.compound,
      primaryMuscles: ['Deltoides anterior y medio'],
      secondaryMuscles: ['Tríceps braquial', 'Trapecio'],
      aliases: ['press militar', 'overhead press', 'ohp', 'shoulder press barra', 'press arnold'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.strength, TrainingGoal.athletic],
    ),
    AtlasExercise(
      id: 'ex_hombros_002',
      name: 'Press de Hombros con Mancuernas',
      muscleGroup: MuscleGroup.hombros,
      equipment: Equipment.mancuernas,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Deltoides anterior y medio'],
      secondaryMuscles: ['Tríceps braquial'],
      aliases: ['press hombros mancuernas', 'dumbbell shoulder press', 'press hombros', 'shoulder press mancuernas'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss, TrainingGoal.health],
    ),
    AtlasExercise(
      id: 'ex_hombros_003',
      name: 'Elevaciones Laterales',
      muscleGroup: MuscleGroup.hombros,
      equipment: Equipment.mancuernas,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Deltoides medio'],
      secondaryMuscles: [],
      aliases: ['elevaciones laterales', 'lateral raise', 'laterales', 'elevaciones', 'lateral raises'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss],
    ),
    AtlasExercise(
      id: 'ex_hombros_004',
      name: 'Face Pull',
      muscleGroup: MuscleGroup.hombros,
      equipment: Equipment.cable,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Deltoides posterior', 'Manguito rotador'],
      secondaryMuscles: ['Romboides', 'Trapecio medio'],
      aliases: ['face pull', 'polea cara', 'face pulls', 'cable face pull'],
      trainingGoals: [TrainingGoal.health, TrainingGoal.athletic],
    ),

    // ── Bíceps ─────────────────────────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_biceps_001',
      name: 'Curl con Barra',
      muscleGroup: MuscleGroup.biceps,
      equipment: Equipment.barra,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Bíceps braquial'],
      secondaryMuscles: ['Braquial', 'Braquiorradial'],
      aliases: ['curl barra', 'barbell curl', 'bicep curl barra', 'curl de biceps barra'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.strength],
    ),
    AtlasExercise(
      id: 'ex_biceps_002',
      name: 'Curl con Mancuernas',
      muscleGroup: MuscleGroup.biceps,
      equipment: Equipment.mancuernas,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Bíceps braquial'],
      secondaryMuscles: ['Braquial', 'Braquiorradial'],
      aliases: ['curl mancuernas', 'dumbbell curl', 'curl alterno', 'bicep curl', 'curl de biceps'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss, TrainingGoal.health],
    ),
    AtlasExercise(
      id: 'ex_biceps_003',
      name: 'Curl en Polea',
      muscleGroup: MuscleGroup.biceps,
      equipment: Equipment.cable,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Bíceps braquial'],
      secondaryMuscles: ['Braquial'],
      aliases: ['curl polea', 'cable curl', 'curl cable', 'polea biceps'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss],
    ),

    // ── Tríceps ────────────────────────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_triceps_001',
      name: 'Extensión de Tríceps en Polea',
      muscleGroup: MuscleGroup.triceps,
      equipment: Equipment.cable,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Tríceps braquial'],
      secondaryMuscles: [],
      aliases: ['extension triceps polea', 'tricep pushdown', 'pushdown', 'polea triceps', 'triceps cable'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss],
    ),
    AtlasExercise(
      id: 'ex_triceps_002',
      name: 'Press Francés',
      muscleGroup: MuscleGroup.triceps,
      equipment: Equipment.barra,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Tríceps braquial'],
      secondaryMuscles: [],
      aliases: ['press frances', 'skull crusher', 'rompe cabezas', 'lying tricep extension', 'press frances barra'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.strength],
    ),
    AtlasExercise(
      id: 'ex_triceps_003',
      name: 'Fondos en Banco',
      muscleGroup: MuscleGroup.triceps,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Tríceps braquial'],
      secondaryMuscles: ['Deltoides anterior'],
      aliases: ['fondos banco', 'bench dips', 'tricep dips', 'fondos en banco triceps'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss, TrainingGoal.health],
    ),

    // ── Cuádriceps / Piernas ───────────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_piernas_001',
      name: 'Sentadilla',
      muscleGroup: MuscleGroup.cuadriceps,
      equipment: Equipment.barra,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.compound,
      primaryMuscles: ['Cuádriceps', 'Glúteo mayor'],
      secondaryMuscles: ['Isquiotibiales', 'Pantorrillas', 'Core'],
      aliases: ['sentadilla', 'squat', 'sentadillas', 'sentadilla libre', 'back squat', 'squat barra'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.strength, TrainingGoal.athletic],
    ),
    AtlasExercise(
      id: 'ex_piernas_002',
      name: 'Prensa de Piernas',
      muscleGroup: MuscleGroup.cuadriceps,
      equipment: Equipment.maquina,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Cuádriceps', 'Glúteo mayor'],
      secondaryMuscles: ['Isquiotibiales'],
      aliases: ['prensa', 'leg press', 'prensa piernas', 'prensa de piernas'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss, TrainingGoal.health],
    ),
    AtlasExercise(
      id: 'ex_piernas_003',
      name: 'Extensión de Cuádriceps',
      muscleGroup: MuscleGroup.cuadriceps,
      equipment: Equipment.maquina,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Cuádriceps'],
      secondaryMuscles: [],
      aliases: ['extension cuadriceps', 'leg extension', 'extensiones piernas', 'extensiones de cuadriceps'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss],
    ),
    AtlasExercise(
      id: 'ex_piernas_004',
      name: 'Curl de Isquiotibiales',
      muscleGroup: MuscleGroup.isquiotibiales,
      equipment: Equipment.maquina,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Isquiotibiales'],
      secondaryMuscles: [],
      aliases: ['curl isquiotibiales', 'leg curl', 'curl femoral', 'femoral', 'hamstring curl'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss, TrainingGoal.health],
    ),
    AtlasExercise(
      id: 'ex_piernas_005',
      name: 'Peso Muerto Rumano',
      muscleGroup: MuscleGroup.isquiotibiales,
      equipment: Equipment.barra,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.compound,
      primaryMuscles: ['Isquiotibiales', 'Glúteo mayor'],
      secondaryMuscles: ['Erectores espinales'],
      aliases: ['peso muerto rumano', 'rdl', 'romanian deadlift', 'rdl mancuernas', 'peso muerto piernas'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.strength, TrainingGoal.athletic],
    ),
    AtlasExercise(
      id: 'ex_piernas_006',
      name: 'Zancadas',
      muscleGroup: MuscleGroup.cuadriceps,
      equipment: Equipment.mancuernas,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Cuádriceps', 'Glúteo mayor'],
      secondaryMuscles: ['Isquiotibiales', 'Pantorrillas'],
      aliases: ['zancadas', 'lunges', 'lunge', 'estocadas', 'dumbbell lunges'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss, TrainingGoal.health, TrainingGoal.athletic],
    ),

    // ── Glúteos ────────────────────────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_gluteos_001',
      name: 'Hip Thrust',
      muscleGroup: MuscleGroup.gluteos,
      equipment: Equipment.barra,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.compound,
      primaryMuscles: ['Glúteo mayor'],
      secondaryMuscles: ['Isquiotibiales', 'Core'],
      aliases: ['hip thrust', 'empuje cadera', 'puente gluteo barra', 'glute bridge barra', 'hip thrust barra'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.health, TrainingGoal.athletic],
    ),
    AtlasExercise(
      id: 'ex_gluteos_002',
      name: 'Abducción de Cadera',
      muscleGroup: MuscleGroup.gluteos,
      equipment: Equipment.maquina,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Glúteo medio', 'Glúteo menor'],
      secondaryMuscles: [],
      aliases: ['abduccion cadera', 'hip abduction', 'abductores', 'maquina abductores'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss, TrainingGoal.health],
    ),

    // ── Core ───────────────────────────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_core_001',
      name: 'Plancha',
      muscleGroup: MuscleGroup.core,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Recto abdominal', 'Transverso abdominal'],
      secondaryMuscles: ['Oblicuos', 'Glúteos', 'Cuádriceps'],
      aliases: ['plancha', 'plank', 'plancha abdominal', 'isometria core'],
      trainingGoals: [TrainingGoal.health, TrainingGoal.athletic, TrainingGoal.fatLoss],
    ),
    AtlasExercise(
      id: 'ex_core_002',
      name: 'Crunch en Polea',
      muscleGroup: MuscleGroup.core,
      equipment: Equipment.cable,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Recto abdominal'],
      secondaryMuscles: ['Oblicuos'],
      aliases: ['crunch polea', 'cable crunch', 'crunch cable', 'crunch en polea'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss],
    ),
    AtlasExercise(
      id: 'ex_core_003',
      name: 'Rueda Abdominal',
      muscleGroup: MuscleGroup.core,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.avanzado,
      movement: MovementPattern.compound,
      primaryMuscles: ['Recto abdominal', 'Transverso abdominal'],
      secondaryMuscles: ['Oblicuos', 'Dorsales', 'Hombros'],
      aliases: ['rueda abdominal', 'ab wheel', 'rueda core', 'rollout', 'ab rollout'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.athletic],
    ),

    // ── Core — salud y estabilidad ─────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_core_004',
      name: 'Bird Dog',
      muscleGroup: MuscleGroup.core,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Transverso abdominal', 'Erectores espinales'],
      secondaryMuscles: ['Glúteo mayor', 'Romboides'],
      aliases: ['bird dog', 'perro pájaro', 'estabilizacion lumbar', 'cuadrupedia'],
      trainingGoals: [TrainingGoal.health],
    ),
    AtlasExercise(
      id: 'ex_core_005',
      name: 'Dead Bug',
      muscleGroup: MuscleGroup.core,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Transverso abdominal', 'Recto abdominal'],
      secondaryMuscles: ['Oblicuos', 'Flexores de cadera'],
      aliases: ['dead bug', 'bicho muerto', 'anti extension core'],
      trainingGoals: [TrainingGoal.health, TrainingGoal.athletic],
    ),

    // ── Espalda baja / Erectores ───────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_espaldabaja_001',
      name: 'Peso Muerto Convencional',
      muscleGroup: MuscleGroup.espalda,
      equipment: Equipment.barra,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.compound,
      primaryMuscles: ['Erectores espinales', 'Isquiotibiales', 'Glúteo mayor'],
      secondaryMuscles: ['Trapecio', 'Romboides', 'Core'],
      aliases: ['peso muerto', 'deadlift', 'peso muerto convencional', 'dl', 'conventional deadlift'],
      trainingGoals: [TrainingGoal.strength, TrainingGoal.hypertrophy, TrainingGoal.athletic],
    ),
    AtlasExercise(
      id: 'ex_espaldabaja_002',
      name: 'Extensión de Espalda',
      muscleGroup: MuscleGroup.espalda,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Erectores espinales'],
      secondaryMuscles: ['Glúteo mayor', 'Isquiotibiales'],
      aliases: ['extension espalda', 'back extension', 'hiperextension', 'hyperextension', 'extension lumbar'],
      trainingGoals: [TrainingGoal.health, TrainingGoal.strength],
    ),
    AtlasExercise(
      id: 'ex_espaldabaja_003',
      name: 'Superman',
      muscleGroup: MuscleGroup.espalda,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Erectores espinales'],
      secondaryMuscles: ['Glúteo mayor', 'Isquiotibiales', 'Romboides'],
      aliases: ['superman', 'extension dorsal', 'elevacion prona', 'back raise'],
      trainingGoals: [TrainingGoal.health],
    ),

    // ── Pantorrillas ───────────────────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_pantorrillas_001',
      name: 'Elevación de Talones de Pie',
      muscleGroup: MuscleGroup.pantorrillas,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Gastrocnemio', 'Sóleo'],
      secondaryMuscles: [],
      aliases: ['elevacion talones', 'calf raise', 'gemelos de pie', 'standing calf raise', 'pantorrillas de pie'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.fatLoss, TrainingGoal.health],
    ),
    AtlasExercise(
      id: 'ex_pantorrillas_002',
      name: 'Elevación de Talones Sentado',
      muscleGroup: MuscleGroup.pantorrillas,
      equipment: Equipment.maquina,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Sóleo'],
      secondaryMuscles: ['Gastrocnemio'],
      aliases: ['elevacion talones sentado', 'seated calf raise', 'gemelos sentado', 'soleo'],
      trainingGoals: [TrainingGoal.hypertrophy],
    ),
    AtlasExercise(
      id: 'ex_pantorrillas_003',
      name: 'Elevación de Talones Unilateral',
      muscleGroup: MuscleGroup.pantorrillas,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.isolation,
      primaryMuscles: ['Gastrocnemio', 'Sóleo'],
      secondaryMuscles: [],
      aliases: ['elevacion talones unilateral', 'single leg calf raise', 'gemelo una pierna'],
      trainingGoals: [TrainingGoal.hypertrophy, TrainingGoal.health],
    ),

    // ── Cardio ─────────────────────────────────────────────────────────────────

    AtlasExercise(
      id: 'ex_cardio_001',
      name: 'Caminata Inclinada',
      muscleGroup: MuscleGroup.fullBody,
      equipment: Equipment.maquina,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.cardio,
      primaryMuscles: ['Glúteo mayor', 'Cuádriceps', 'Sistema cardiovascular'],
      secondaryMuscles: ['Pantorrillas', 'Core'],
      aliases: ['caminata inclinada', 'incline walk', 'treadmill incline', 'cinta inclinada', 'caminadora'],
      trainingGoals: [TrainingGoal.health, TrainingGoal.fatLoss],
    ),
    AtlasExercise(
      id: 'ex_cardio_002',
      name: 'Bicicleta Estática',
      muscleGroup: MuscleGroup.fullBody,
      equipment: Equipment.maquina,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.cardio,
      primaryMuscles: ['Cuádriceps', 'Sistema cardiovascular'],
      secondaryMuscles: ['Isquiotibiales', 'Glúteo mayor'],
      aliases: ['bicicleta estatica', 'stationary bike', 'bike', 'cycling', 'ciclismo indoor', 'spinning'],
      trainingGoals: [TrainingGoal.health, TrainingGoal.fatLoss],
    ),

    // ── Full body / Rendimiento deportivo ──────────────────────────────────────

    AtlasExercise(
      id: 'ex_fullbody_001',
      name: 'Farmer Walk',
      muscleGroup: MuscleGroup.fullBody,
      equipment: Equipment.mancuernas,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Trapecio', 'Core', 'Cuádriceps'],
      secondaryMuscles: ['Glúteo mayor', 'Pantorrillas', 'Antebrazos'],
      aliases: ['farmer walk', 'farmer carry', 'cargada del granjero', 'marcha del granjero', 'loaded carry'],
      trainingGoals: [TrainingGoal.strength, TrainingGoal.athletic, TrainingGoal.health],
    ),
    AtlasExercise(
      id: 'ex_fullbody_002',
      name: 'Kettlebell Swing',
      muscleGroup: MuscleGroup.fullBody,
      equipment: Equipment.kettlebell,
      difficulty: Difficulty.intermedio,
      movement: MovementPattern.compound,
      primaryMuscles: ['Glúteo mayor', 'Isquiotibiales'],
      secondaryMuscles: ['Core', 'Hombros', 'Cuádriceps'],
      aliases: ['kettlebell swing', 'swing kettlebell', 'swing pesa rusa', 'hip hinge swing'],
      trainingGoals: [TrainingGoal.athletic, TrainingGoal.fatLoss, TrainingGoal.health],
    ),
    AtlasExercise(
      id: 'ex_fullbody_003',
      name: 'Burpee',
      muscleGroup: MuscleGroup.fullBody,
      equipment: Equipment.pesoCorporal,
      difficulty: Difficulty.principiante,
      movement: MovementPattern.compound,
      primaryMuscles: ['Cuádriceps', 'Pectoral mayor', 'Sistema cardiovascular'],
      secondaryMuscles: ['Glúteo mayor', 'Tríceps braquial', 'Core'],
      aliases: ['burpee', 'burpees', 'burpe', 'sentadilla-plancha-salto'],
      trainingGoals: [TrainingGoal.fatLoss, TrainingGoal.athletic, TrainingGoal.health],
    ),
  ];

  /// Lista completa. Usar ExerciseSearch para queries.
  static List<AtlasExercise> get all => _all;

  /// Búsqueda directa por ID.
  static AtlasExercise? byId(String id) {
    for (final e in _all) {
      if (e.id == id) return e;
    }
    return null;
  }

  /// Grupos musculares presentes en la biblioteca (en orden de presentación).
  static List<MuscleGroup> get muscleGroups => const [
        MuscleGroup.pecho,
        MuscleGroup.espalda,
        MuscleGroup.hombros,
        MuscleGroup.biceps,
        MuscleGroup.triceps,
        MuscleGroup.cuadriceps,
        MuscleGroup.isquiotibiales,
        MuscleGroup.gluteos,
        MuscleGroup.pantorrillas,
        MuscleGroup.core,
      ];
}
